### ISSUE TITLE
Photos: Apostrophe's in Album name watermark photos with &apos;

### ISSUE THREAD

**Issue by Rvice** [Admidio/admidio#1467]
**Describe the bug**

**To Reproduce**
1. Go to Photos
2. Create an album called "Testy's Photos"
3. Add the Photos of "Just some of Testy's Photos"
4. Upload a photo to the album
5. Open a picture from the album
6. Observe the watermark is "Just some of Testy&apos;s Photos"

**Expected behavior**
I expect the watermark to read "Testy's Photos" as the album name. Additionally, it should use the Album Name and not the "Photos of" value that way it's easier to figure out where the pictures are. Plus, the album being shorter would use up less watermark space.

**Screenshots**
![image](https://github.com/Admidio/admidio/assets/1831523/74ed7653-af04-421b-ab74-e7ea8620fd7e)

**System (please complete the following information):**
 - Admidio-Version 4.2.9 and 4.3.0 Beta 1

**Additional context**
Created an album in the playground
https://www.admidio.org/playground/adm_program/modules/photos/photos.php?photo_uuid=d15025cb-d106-4b17-a05f-a39abd7a0847 open up one of the images

**Comment by Fasse** [comment]
The issue with the apostrophe is fixed.

The watermark should be something like a copyright and not an information about the album. So we show the photographers name or if not filled the text out of the preferences.

**Comment by Rvice** [comment]
Hmm, how can the "photographers name" get added to the photo, I don't see this as an option. I tried the meta information in the image file by putting in the "author" but still no luck.

**Comment by Fasse** [comment]
You must fill the watermark preference with something and than add a photographer name to the album. After that the photographer name will be shown within the photo.

**Comment by Rvice** [comment]
Hmm, I looked in the Photo's preferences and found nothing there about enabling the photographer. Maybe it's a poor translation of this page?
![image](https://github.com/Admidio/admidio/assets/1831523/ee1af09e-e505-4536-9d0d-e22b863bae3f)
i.e. "Photos of" should be "Photographer"?

**Comment by Fasse** [comment]
I mean "Photos of". Sorry.

**Comment by Rvice** [comment]
Observed that "Unidentified" is the default "Photos of" in the album. Trying to blank that field always reverts to "Unidentified"

Seems the watermark setting is not related to the copyright. Easy fix here to reduce the confusing is to change "Photos of" to "Photos by" and add context to indicate "this is displayed in the copyright of the photo"

**Comment by Fasse** [comment]
I have already revised this behavior within the next version. There you could leave it blank.

**Comment by Fasse** [comment]
> Seems the watermark setting is not related to the copyright. Easy fix here to reduce the confusing is to change "Photos of" to "Photos by" and add context to indicate "this is displayed in the copyright of the photo"
Thanks for the hint with "Photos by". I will change that. I already changed the description of the watermark preference for the next major version.

**Comment by Fasse** [comment]
After fixing this, the bug was introduced again in version 4.2.11.
Now it will be fixed within 4.2.12
